server:
  port: ${PORT}

accurate:
  calculatorRegistry:
    username: ${ACCURATE_USERNAME}
    password: ${ACCURATE_PASSWORD}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${ACCURATE_URL}
  instance:
    hostname: ${APP_DOMAIN_NAME}
    non-secure-port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/accurate-calculator-db
    username: postgres
    password: accurate
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enable: Always
logging:
  level:
    com.accurate: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO